/**
 * The shard format and the merge behind `docs/verification/a11y.json` (ADR-0039).
 *
 * `a11y.spec.ts` runs under `fullyParallel`, so its scans are spread across
 * worker *processes*. Nothing they could share in memory would survive that,
 * and a reporter that appended to one file would interleave. Each scan
 * therefore writes its own small JSON file and this module merges them once,
 * from Playwright's `globalTeardown`.
 *
 * The merge is deliberately conservative: it rewrites the committed artifact
 * only when every scan the matrix declares has produced a shard. A partial run
 * — `--grep`, a crash, a single-route debug — leaves the committed baseline
 * alone rather than replacing it with a subset that would read as "these are
 * all the violations there are".
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

export interface Finding {
  id: string;
  impact: string | null;
  nodes: number;
  target: string;
  help: string;
}

export interface Shard {
  key: string;
  routeId: string;
  where: string;
  findings: Finding[];
}

export const SHARD_DIR = fileURLToPath(new URL("../../test-results/a11y/", import.meta.url));

const MATRIX_PATH = fileURLToPath(new URL("../../../docs/a11y/routes.json", import.meta.url));
const GUIDE_DIR = fileURLToPath(new URL("../../src/pages/guide/", import.meta.url));
const ARTIFACT = fileURLToPath(new URL("../../../docs/verification/a11y.json", import.meta.url));

function matrix(): any {
  return JSON.parse(readFileSync(MATRIX_PATH, "utf8"));
}

/** How many routes the matrix resolves to, with `expand` rules applied. */
function routeCount(m: any): number {
  let count = 0;
  for (const entry of m.routes) {
    if (entry.expand === "guide-chapters") {
      count += readdirSync(GUIDE_DIR).filter((f) => f.endsWith(".md")).length;
    } else {
      count += 1;
    }
  }
  return count;
}

/** Routes x viewports x themes, plus one forced-colors pass, plus the states. */
export function expectedScans(m = matrix()): number {
  const perRoute = m.viewports.length * m.themes.length + m.modes.length;
  return routeCount(m) * perRoute + m.states.length;
}

/** Wipe the shard directory so a partial run cannot inherit a previous one's. */
export function resetShards(): void {
  rmSync(SHARD_DIR, { recursive: true, force: true });
  mkdirSync(SHARD_DIR, { recursive: true });
}

export function mergeShards(): void {
  if (!existsSync(SHARD_DIR)) return;

  const shards: Shard[] = readdirSync(SHARD_DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => JSON.parse(readFileSync(join(SHARD_DIR, f), "utf8")));

  if (shards.length === 0) return;

  const expected = expectedScans();
  if (shards.length < expected) {
    console.log(
      `[a11y] ${shards.length} of ${expected} scans ran — leaving ` +
        `docs/verification/a11y.json alone. Run \`make test-a11y\` for the full matrix.`,
    );
    return;
  }

  const m = matrix();
  const byRoute: Record<string, Record<string, Finding & { where: string[] }>> = {};

  for (const shard of shards.sort((a, b) => a.key.localeCompare(b.key))) {
    for (const f of shard.findings) {
      const bucket = (byRoute[shard.routeId] ??= {});
      const existing = bucket[f.id];
      if (existing) {
        existing.nodes += f.nodes;
        existing.where.push(shard.where);
        // Keep the worst impact seen, so a rule that is moderate at one
        // viewport and serious at another is reported as serious.
        if (f.impact === "critical" || (f.impact === "serious" && existing.impact !== "critical")) {
          existing.impact = f.impact;
        }
      } else {
        bucket[f.id] = { ...f, where: [shard.where] };
      }
    }
  }

  const routes = Object.keys(byRoute).sort();
  const totals = { violations: 0, nodes: 0, critical: 0, serious: 0, moderate: 0, minor: 0 };
  const report = routes.map((routeId) => {
    const findings = Object.values(byRoute[routeId]).sort((a, b) => b.nodes - a.nodes);
    for (const f of findings) {
      totals.violations += 1;
      totals.nodes += f.nodes;
      const impact = (f.impact ?? "minor") as keyof typeof totals;
      if (impact in totals) (totals[impact] as number) += 1;
    }
    return {
      route: routeId,
      violations: findings.map((f) => ({
        id: f.id,
        impact: f.impact,
        nodes: f.nodes,
        firstTarget: f.target,
        help: f.help,
        seenAt: [...new Set(f.where)].sort(),
      })),
    };
  });

  writeFileSync(
    ARTIFACT,
    `${JSON.stringify(
      {
        _comment:
          "Generated by `make test-a11y` (ADR-0039). Do not hand-edit — re-run the target. " +
          "Every route in docs/a11y/routes.json, scanned by axe-core against the WCAG 2.1 AA " +
          "tag set at three viewports, in both themes, and once with forced-colors: active, " +
          "plus the interactive states. Routes with no entry here had no violations.",
        axeTags: m.axeTags,
        scans: shards.length,
        routesWithViolations: routes.length,
        totals,
        routes: report,
      },
      null,
      2,
    )}\n`,
  );

  console.log(
    `[a11y] ${shards.length} scans → docs/verification/a11y.json ` +
      `(${totals.violations} violation/route pairs, ${totals.nodes} nodes)`,
  );
}
