"""`python -m ingest load` orchestration: parse one title file into Postgres.

Dedupe rule (PLAN §3/§9.10): a section's content is identified by
`(section_id, content_hash)`. If that pair already has a `SectionVersion`, this
release is linked to the *existing* row via `section_release_map` — no new
`section_versions` row, no duplicate storage. Only genuinely new content
creates a new version, with `first_release_id` set to the release doing the
creating.

The hash is taken over `SectionRecord.content_key` — the section XML with its
`@id` guids removed — and never over the raw XML, which changes at every release
point because guids are regenerated by design (ADR-0007).

Everything here talks to `db.models` directly; it is the ingest side of the
Repository boundary (CLAUDE.md architecture rule 1 governs `api/`, not this).
"""

from __future__ import annotations

import hashlib
import sys
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Any

from sqlalchemy import func, select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.orm import Session

from db.models import (
    GuidMap,
    ReleasePoint,
    Section,
    SectionReleaseMap,
    SectionVersion,
    StructureNode,
    Title,
    TitleVersion,
)
from ingest import inventory as inventory_mod
from ingest.parser import parser_for
from ingest.records import DocumentMeta
from ingest.release_label import parse_label
from ingest import search_sync

GUID_BATCH_SIZE = 500


class MissingCurrencyDateError(ValueError):
    """Raised when a release point is being created for the first time and neither
    `--currency-date` nor the release-point inventory supplies a date. Source USLM
    files carry no currency date of their own (verified against usc16.xml) — it has
    to come from the caller or from `data/uscreleasepoints.json`, never the XML."""


@dataclass
class LoadStats:
    """What one `load_release` call did, for the CLI summary and the manifest."""

    release_label: str
    title_num: str
    schema_version: str
    raw_section_elements: int
    sections_ingested: int
    new_section_versions: int
    deduped_section_versions: int
    structure_nodes: int = 0
    status_counts: dict[str, int] = field(default_factory=dict)


def load_release(
    xml_path: Path,
    release_label: str,
    session: Session,
    *,
    currency_date: date | None = None,
    source_zip: Path | None = None,
    defer_version_changes: bool = False,
) -> LoadStats:
    """Parse `xml_path` and load it into Postgres under `release_label`.

    `defer_version_changes` skips the ADR-0074 hook at the bottom. What a bulk
    run passes when it will follow with one `python -m ingest version-changes`
    over the corpus — which computes each section once instead of once per
    release point that touched it — and what `deploy/update-corpus.sh` already
    runs after every load anyway.
    """
    parser = parser_for(xml_path)
    meta = parser.parse_meta(xml_path)
    if not meta.doc_number:
        raise ValueError(f"{xml_path}: <docNumber> missing, cannot determine title")

    search_sync.create_indices()

    release = _get_or_create_release(session, release_label, currency_date)
    title = _get_or_create_title(session, meta)
    title_version = _get_or_create_title_version(
        session, title, release, xml_path, meta, source_zip
    )
    # Any earlier attempt at this (title, release) is being redone from the top;
    # don't leave a stale completion count standing while it runs.
    title_version.sections_loaded = None
    structure_nodes = _load_structure(session, parser, xml_path, title, release)
    session.commit()

    existing_sections = {
        s.identifier: s
        for s in session.scalars(select(Section).where(Section.title_id == title.id))
    }
    existing_versions: dict[int, dict[bytes, SectionVersion]] = {}
    if existing_sections:
        section_ids = [s.id for s in existing_sections.values()]
        for version in session.scalars(
            select(SectionVersion).where(SectionVersion.section_id.in_(section_ids))
        ):
            existing_versions.setdefault(version.section_id, {})[version.content_hash] = version

    status_counts: dict[str, int] = {}
    new_versions = 0
    deduped = 0
    sections_ingested = 0
    guid_rows: list[dict[str, object]] = []
    versions_to_sync: list[dict[str, Any]] = []
    retire_keys: list[tuple[str, int]] = []
    # Identifiers this release has already created a *new* version for. A second
    # one means the source published two elements under the one identifier at
    # this release point (ADR-0021) — and since the index document is keyed on
    # (identifier, first release), both are the same document. The second write
    # overwrites the first and flags it, which is why flagging only the later
    # occurrence is enough.
    new_version_identifiers: set[str] = set()
    # What this load maps where, for the version-change hook at the bottom
    # (ADR-0074): every section it touched, the version group each one landed
    # on (a set — the source can publish several elements under one identifier
    # at one release, ADR-0021), and the sections that gained a new group.
    # `version_changes.sections_needing_recompute` decides which of them can
    # actually have different change rows; recomputing all of them is a
    # whole-title pass per release load.
    mapped_versions: dict[int, set[int]] = {}
    new_version_sections: set[int] = set()

    # Only text from the newest release this title has reached is "in force", and
    # loads do not have to arrive in order — `load-all` walks the inventory's seq,
    # but a single `python -m ingest load` of an old release point can follow a
    # newer one. Loading backwards must not relabel superseded text as current, so
    # the comparison is against the newest *completed* load of this title
    # (`sections_loaded` is stamped last, so this load itself is still NULL here).
    newest_loaded_seq = session.scalar(
        select(func.max(ReleasePoint.seq))
        .select_from(TitleVersion)
        .join(ReleasePoint, ReleasePoint.id == TitleVersion.release_id)
        .where(
            TitleVersion.title_id == title.id,
            TitleVersion.sections_loaded.is_not(None),
        )
    )
    is_newest_for_title = newest_loaded_seq is None or release.seq >= newest_loaded_seq

    # Captured before the loop: `session.commit()` expires the instance, and
    # re-reading these off `release` per section would re-SELECT it after every
    # batch commit.
    release_id = release.id
    release_seq = release.seq
    release_label = release.label

    for record in parser.iter_sections(xml_path):
        section = existing_sections.get(record.identifier)
        if section is None:
            section = Section(title_id=title.id, identifier=record.identifier)
            session.add(section)
            session.flush()
            existing_sections[record.identifier] = section

        # Hash the guid-stripped form, not the raw XML: guids regenerate at every
        # release point, so raw XML never repeats and dedupe would collapse nothing
        # (ADR-0007). `record.xml` is still what gets stored, verbatim.
        content_hash = hashlib.sha256(record.content_key.encode("utf-8")).digest()
        siblings = existing_versions.get(section.id, {})
        version = siblings.get(content_hash)
        if version is None:
            # Everything this section said before is now superseded. Collected
            # before the new row joins `siblings`, and only when this release is
            # the title's newest — a backfill of an older release point creates
            # versions that were never current and retires nothing.
            if is_newest_for_title:
                retire_keys.extend(
                    (record.identifier, sibling.first_release_id)
                    for sibling in siblings.values()
                    if sibling.first_release_id != release.id
                )
            version = SectionVersion(
                section_id=section.id,
                first_release_id=release.id,
                content_hash=content_hash,
                xml=record.xml,
                num=record.num,
                heading=record.heading,
                status=record.status,
                source_credit=record.source_credit,
                text_hash=record.text_hash or None,
                notes_hash=record.notes_hash or None,
            )
            session.add(version)
            session.flush()
            existing_versions.setdefault(section.id, {})[content_hash] = version
            new_versions += 1
            new_version_sections.add(section.id)


            versions_to_sync.append({
                "identifier": record.identifier,
                "num": record.num,
                "heading": record.heading,
                "xml": record.xml,
                "status": record.status,
                "version_id": version.id,
                # Where this text sits, for `chapter:` and `?sort=citation`.
                # The same two values written to `section_release_map` below,
                # read from the record rather than from that row so the index
                # write does not wait on the upsert.
                "parent_identifier": record.ancestors[-1][1] if record.ancestors else None,
                "seq_in_title": record.seq,
                "id_collision": record.identifier in new_version_identifiers,
                "first_release_id": release_id,
                "first_release_seq": release_seq,
                "first_release_label": release_label,
                "is_current": is_newest_for_title,
            })
            new_version_identifiers.add(record.identifier)
        else:
            # A release republishing this text unchanged needs no index write at
            # all: the document already exists and is already current. This is
            # why sync stays cheap at 91% dedupe (ADR-0028).
            deduped += 1

        mapped_versions.setdefault(section.id, set()).add(version.id)

        # Reading order and parent are this release point's, even when the text
        # deduped into a version created by an earlier one (ADR-0008).
        placement = {
            "seq_in_title": record.seq,
            "parent_identifier": record.ancestors[-1][1] if record.ancestors else None,
        }
        session.execute(
            pg_insert(SectionReleaseMap)
            .values(section_version_id=version.id, release_id=release.id, **placement)
            .on_conflict_do_update(
                index_elements=["section_version_id", "release_id"], set_=placement
            )
        )

        for guid_ref in record.guid_refs:
            guid_rows.append(
                {"guid": guid_ref.guid, "release_id": release.id, "identifier": guid_ref.identifier}
            )
        if len(guid_rows) >= GUID_BATCH_SIZE:
            _flush_guid_rows(session, guid_rows)
            guid_rows.clear()
            session.commit()
            # After the commit, never before: indexing text whose transaction
            # then rolled back would advertise a section the database has not got.
            _flush_search(versions_to_sync, retire_keys)

        if record.status:
            status_counts[record.status] = status_counts.get(record.status, 0) + 1
        sections_ingested += 1

    if guid_rows:
        _flush_guid_rows(session, guid_rows)

    raw_count = parser.count_section_elements(xml_path)

    # The completion marker, written last and committed with the final batch:
    # until this lands, `sections_loaded` is NULL and `load-all` treats the
    # (title, release) as unloaded and redoes it.
    title_version.sections_loaded = sections_ingested
    title_version.raw_section_elements = raw_count
    session.commit()
    _flush_search(versions_to_sync, retire_keys)

    # Incremental version-change hook (ADR-0074). Runs after the load has
    # committed, over the sections whose change rows this release can actually
    # have moved (`sections_needing_recompute` documents the four cases), in
    # committed batches. A failure warns loudly instead of failing the load —
    # the load itself is complete — and then *deletes* the change rows it was
    # recomputing, so the failure outlives the warning: the resume skip is a
    # count equality, which sees a missing row and not a stale one.
    if defer_version_changes and mapped_versions:
        # A deferral has to leave the database saying so. The follow-up pass
        # resumes on a count equality, which sees a missing change row and not
        # a stale one — so the rows this hook would have rewritten are deleted
        # here, exactly as a failed hook deletes them. Without this the pass
        # would skip as complete every section whose group *range* moved
        # (`sections_needing_recompute`'s cases 3 and 4) and leave
        # `window_from_release_id`, `attribution` and `concurrent` stale on
        # them. During a bulk load of a corpus that has no change rows yet —
        # what the flag is for — the delete matches nothing and costs an index
        # probe.
        from ingest import version_changes

        stale = (
            sorted(mapped_versions)
            if is_newest_for_title
            # A load below the title's newest can move a window for a section
            # it never touched; `sections_needing_recompute` returns the whole
            # title for that case and so does this.
            else sorted(section.id for section in existing_sections.values())
        )
        try:
            version_changes.clear_change_rows(session, stale)
            session.commit()
        except Exception as exc:
            session.rollback()
            print(
                f"WARNING: could not mark {len(stale)} sections of title "
                f"{meta.doc_number} @ {release_label} for the deferred "
                f"version-change pass ({type(exc).__name__}: {exc}) — run "
                f"`python -m ingest version-changes --title {meta.doc_number} "
                "--recompute` after the load rather than the plain pass",
                file=sys.stderr,
            )
    elif mapped_versions:
        from ingest import version_changes

        recompute_ids: set[int] = set()
        try:
            version_changes.warn_if_unclassified(
                session,
                f"the version-change rows for title {meta.doc_number} "
                f"@ {release_label}",
            )
            recompute_ids = version_changes.sections_needing_recompute(
                session,
                title_id=title.id,
                release_id=release_id,
                mapped_versions=mapped_versions,
                new_version_sections=new_version_sections,
            )
            version_changes.compute_in_batches(session, sorted(recompute_ids))
        except Exception as exc:
            session.rollback()
            print(
                f"WARNING: version-change recompute failed for "
                f"{len(recompute_ids)} sections of title {meta.doc_number} "
                f"@ {release_label} ({type(exc).__name__}: {exc}) — the load "
                "itself is complete; re-derive the rows with `python -m ingest "
                f"version-changes --title {meta.doc_number} --recompute`",
                file=sys.stderr,
            )
            try:
                version_changes.clear_change_rows(session, sorted(recompute_ids))
                session.commit()
            except Exception as clear_exc:  # pragma: no cover - the database is gone
                session.rollback()
                print(
                    "WARNING: could not clear the stale change rows either "
                    f"({type(clear_exc).__name__}: {clear_exc}) — the next "
                    "`version-changes` run will skip these sections as complete "
                    "until they are recomputed by hand",
                    file=sys.stderr,
                )

    return LoadStats(
        release_label=release_label,
        title_num=meta.doc_number,
        schema_version=meta.schema_version,
        raw_section_elements=raw_count,
        sections_ingested=sections_ingested,
        new_section_versions=new_versions,
        deduped_section_versions=deduped,
        structure_nodes=structure_nodes,
        status_counts=status_counts,
    )


def _load_structure(
    session: Session,
    parser,
    xml_path: Path,
    title: Title,
    release: ReleasePoint,
) -> int:
    """Upsert the title's hierarchy from the parser's TOC pass.

    Nodes are keyed on `(title_id, identifier)` and updated in place: headings do
    change (a chapter gets renamed), but the node is the same node, and `sections`
    already points at it by identifier. Release bookkeeping goes by `seq`, not by
    ingest order, so loading an older release point after a newer one — which is
    exactly what a bulk load does — still leaves `first_release_id` on the older.

    **The descriptive fields follow the newest release loaded, never the last one
    written.** The table holds one row per node with no per-release history (the
    standing debt), so something has to decide which release's view it shows;
    "whichever load ran most recently" is not an answer. Title 16's
    `/us/usc/t16/ch1/schXCVII` is `repealed` in 2013 and `reserved` in 2026, and
    loading the 2013 file after the 2026 one silently relabelled it — caught by
    `test_the_reserved_subchapter_is_retrievable_and_badged` during the first bulk
    load. Gating on `seq` makes the outcome independent of load order.
    """
    existing = {
        node.identifier: node
        for node in session.scalars(
            select(StructureNode).where(StructureNode.title_id == title.id)
        )
    }
    seq_by_release: dict[int, int] = {
        release_id: seq
        for release_id, seq in session.execute(
            select(ReleasePoint.id, ReleasePoint.seq)
        ).all()
    }
    ids_by_identifier = {identifier: node.id for identifier, node in existing.items()}
    guid_rows: list[dict[str, object]] = []
    nodes_to_sync: list[dict[str, Any]] = []
    count = 0

    for record in parser.iter_structure(xml_path):
        parent_id = (
            ids_by_identifier.get(record.parent_identifier)
            if record.parent_identifier
            else None
        )
        node = existing.get(record.identifier)
        this_seq = seq_by_release[release.id]
        if node is None:
            node = StructureNode(
                title_id=title.id,
                identifier=record.identifier,
                first_release_id=release.id,
                last_release_id=release.id,
            )
            session.add(node)
            existing[record.identifier] = node
            describes_node = True
        else:
            # Decided before last_release_id moves, or every release looks newest.
            describes_node = this_seq >= seq_by_release[node.last_release_id]
            if this_seq < seq_by_release[node.first_release_id]:
                node.first_release_id = release.id
            if this_seq > seq_by_release[node.last_release_id]:
                node.last_release_id = release.id

        if describes_node:
            node.level = record.level
            node.num = record.num
            node.num_value = record.num_value
            node.heading = record.heading
            node.status = record.status
            node.parent_id = parent_id
            node.seq = record.seq
            node.depth = record.depth
            
            nodes_to_sync.append({
                "identifier": record.identifier,
                "level": record.level,
                "num_value": record.num_value,
                "heading": record.heading,
            })
            
        if record.depth == 0 and record.heading and title.name == _fallback_title_name(title.num):
            # USLM 1.0.15 has no <dc:title>, so ingest names titles "Title 16" and
            # the real name — CONSERVATION — is only on the root structural element.
            title.name = record.heading
        session.flush()  # pre-order guarantees the parent's id exists for its children
        ids_by_identifier[record.identifier] = node.id

        if record.guid:
            guid_rows.append(
                {
                    "guid": record.guid,
                    "release_id": release.id,
                    "identifier": record.identifier,
                }
            )
        count += 1

    if guid_rows:
        # Chapter guids belong in guid_map too: `?id=` must resolve any @id in the
        # file, not only the ones inside sections (ADR-0003).
        _flush_guid_rows(session, guid_rows)
    if nodes_to_sync:
        search_sync.sync_structure_nodes(nodes_to_sync)
    return count


def _flush_search(
    versions_to_sync: list[dict[str, Any]], retire_keys: list[tuple[str, int]]
) -> None:
    """Push one batch of index changes and empty the buffers.

    Retire first, so a reader mid-load sees no text at all for a changed section
    rather than two competing "current" versions of it.
    """
    if retire_keys:
        search_sync.retire_versions(retire_keys)
        retire_keys.clear()
    if versions_to_sync:
        search_sync.sync_sections(versions_to_sync)
        versions_to_sync.clear()


def _flush_guid_rows(session: Session, rows: list[dict[str, object]]) -> None:
    stmt = pg_insert(GuidMap).values(rows)
    stmt = stmt.on_conflict_do_update(
        index_elements=["guid"],
        set_={"release_id": stmt.excluded.release_id, "identifier": stmt.excluded.identifier},
    )
    session.execute(stmt)


def _get_or_create_release(
    session: Session, label: str, currency_date: date | None
) -> ReleasePoint:
    """Find the release point, or create it from the inventory (or an explicit date).

    Normal path once `python -m ingest inventory` has run: the row already exists
    with its real `currency_date` and true global `seq`, and this is a lookup.
    `--currency-date` remains for loading a release the inventory doesn't list.
    """
    existing = session.scalars(
        select(ReleasePoint).where(ReleasePoint.label == label)
    ).first()
    if existing is not None:
        return existing

    entry = _inventory_entry(label)
    if currency_date is None:
        if entry is None:
            raise MissingCurrencyDateError(
                f"release {label!r} is neither in the database nor in "
                f"{inventory_mod.INVENTORY_PATH} (run `python -m ingest inventory`), "
                "and no --currency-date was given"
            )
        currency_date = entry.currency_date

    parsed = parse_label(label)
    if entry is not None:
        seq = entry.seq
    else:
        # No inventory row: park the release after everything known rather than
        # inventing an ordering. `python -m ingest inventory` renumbers on its next
        # run, and until then this label only orders against itself.
        max_seq = session.scalars(select(func.max(ReleasePoint.seq))).first()
        seq = 0 if max_seq is None else max_seq + 1

    release = ReleasePoint(
        congress=parsed.congress,
        law_num=parsed.law_num,
        excluded_laws=list(parsed.excluded_laws),
        update_num=parsed.update_num,
        label=label,
        currency_date=currency_date,
        seq=seq,
    )
    session.add(release)
    session.flush()
    return release


def _inventory_entry(label: str) -> inventory_mod.ReleasePointEntry | None:
    """The inventory's record for `label`, if the inventory has been fetched."""
    if not inventory_mod.INVENTORY_PATH.exists():
        return None
    for entry in inventory_mod.read_inventory():
        if entry.label == label:
            return entry
    return None


def _get_or_create_title(session: Session, meta: DocumentMeta) -> Title:
    num = meta.doc_number
    assert num is not None
    existing = session.scalars(select(Title).where(Title.num == num)).first()
    if existing is not None:
        return existing
    title = Title(
        num=num,
        name=meta.doc_title or _fallback_title_name(num),
        is_positive_law=bool(meta.is_positive_law) if meta.is_positive_law is not None else False,
    )
    session.add(title)
    session.flush()
    return title


def _fallback_title_name(num: str) -> str:
    return f"Title {num}"


def _get_or_create_title_version(
    session: Session,
    title: Title,
    release: ReleasePoint,
    xml_path: Path,
    meta: DocumentMeta,
    source_zip: Path | None = None,
) -> TitleVersion:
    existing = session.scalars(
        select(TitleVersion).where(
            TitleVersion.title_id == title.id, TitleVersion.release_id == release.id
        )
    ).first()
    if existing is not None:
        return existing
    title_version = TitleVersion(
        title_id=title.id,
        release_id=release.id,
        # The published artifact is the zip; hash that when we have it, so a
        # re-download can be checked byte-for-byte. Falls back to the XML for files
        # that arrived unzipped (the repo samples).
        source_zip_sha256=_sha256_file(source_zip or xml_path),
        schema_version=meta.schema_version,
    )
    session.add(title_version)
    session.flush()
    return title_version


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()
