"""Record titles_affected on release_points

Revision ID: 111ae2b5d127
Revises: 9b1ce4ea7ddf
Create Date: 2026-07-27 22:55:41.361024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '111ae2b5d127'
down_revision: Union[str, Sequence[str], None] = '9b1ce4ea7ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Existing rows get an empty list — "we don't know what this release changed" —
    which `python -m ingest inventory` fills on its next run. An empty list is not
    the same claim as "changed nothing", and callers read it as unknown.
    """
    op.add_column(
        "release_points",
        sa.Column(
            "titles_affected",
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default="{}",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release_points', 'titles_affected')
    # ### end Alembic commands ###
