"""Add structure_nodes and section_versions.parent_identifier

Revision ID: 1a045cde2094
Revises: eab62d9362f4
Create Date: 2026-07-27 22:40:14.434523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a045cde2094'
down_revision: Union[str, Sequence[str], None] = 'eab62d9362f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structure_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('num', sa.String(), nullable=True),
    sa.Column('num_value', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('first_release_id', sa.Integer(), nullable=False),
    sa.Column('last_release_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_release_id'], ['release_points.id'], ),
    sa.ForeignKeyConstraint(['last_release_id'], ['release_points.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['structure_nodes.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_id', 'identifier')
    )
    op.create_index('ix_structure_nodes_parent_id_seq', 'structure_nodes', ['parent_id', 'seq'], unique=False)
    op.add_column('section_versions', sa.Column('parent_identifier', sa.String(), nullable=True))
    op.create_index('ix_section_versions_parent_identifier_seq', 'section_versions', ['parent_identifier', 'seq_in_title'], unique=False)
    op.create_index('ix_sections_identifier', 'sections', ['identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sections_identifier', table_name='sections')
    op.drop_index('ix_section_versions_parent_identifier_seq', table_name='section_versions')
    op.drop_column('section_versions', 'parent_identifier')
    op.drop_index('ix_structure_nodes_parent_id_seq', table_name='structure_nodes')
    op.drop_table('structure_nodes')
    # ### end Alembic commands ###
