"""title_versions load completion counts

Revision ID: 4678d590a1a9
Revises: 111ae2b5d127
Create Date: 2026-07-28 12:53:41.243121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4678d590a1a9'
down_revision: Union[str, Sequence[str], None] = '111ae2b5d127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title_versions', sa.Column('sections_loaded', sa.Integer(), nullable=True))
    op.add_column('title_versions', sa.Column('raw_section_elements', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('title_versions', 'raw_section_elements')
    op.drop_column('title_versions', 'sections_loaded')
    # ### end Alembic commands ###
