"""Add release_points.update_num for u1 release labels

Revision ID: eab62d9362f4
Revises: aef3da4cc2e9
Create Date: 2026-07-27 22:33:54.136151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab62d9362f4'
down_revision: Union[str, Sequence[str], None] = 'aef3da4cc2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release_points', sa.Column('update_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release_points', 'update_num')
    # ### end Alembic commands ###
