"""initial schema

Revision ID: fce3a6c7a647
Revises: 
Create Date: 2026-07-27 14:06:22.436047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fce3a6c7a647'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('congress', sa.Integer(), nullable=False),
    sa.Column('law_num', sa.Integer(), nullable=False),
    sa.Column('excluded_laws', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('currency_date', sa.Date(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('seq')
    )
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_positive_law', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('guid_map',
    sa.Column('guid', sa.String(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['release_points.id'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_id', 'identifier')
    )
    op.create_table('title_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('source_zip_sha256', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unchanged_from_release_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['release_points.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.ForeignKeyConstraint(['unchanged_from_release_id'], ['release_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('first_release_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.LargeBinary(), nullable=False),
    sa.Column('xml', sa.Text(), nullable=False),
    sa.Column('html_cache', sa.Text(), nullable=True),
    sa.Column('num', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('seq_in_title', sa.Integer(), nullable=False),
    sa.Column('source_credit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['first_release_id'], ['release_points.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'content_hash', 'first_release_id')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('pinned_release_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pinned_release_id'], ['release_points.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section_release_map',
    sa.Column('section_version_id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['release_points.id'], ),
    sa.ForeignKeyConstraint(['section_version_id'], ['section_versions.id'], ),
    sa.PrimaryKeyConstraint('section_version_id', 'release_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_release_map')
    op.drop_table('watchlist_items')
    op.drop_table('section_versions')
    op.drop_table('watchlists')
    op.drop_table('title_versions')
    op.drop_table('sections')
    op.drop_table('guid_map')
    op.drop_table('users')
    op.drop_table('titles')
    op.drop_table('release_points')
    # ### end Alembic commands ###
