/**
 * How many characters a line of statutory text holds, and what that costs in
 * scroll length.
 *
 * The reading measure is a brand decision (ADR-0052) and it is stated as a
 * width — `--measure` — while the thing it is meant to control is a character
 * count. Those two are related only through the face and the size, so a face
 * change moves the count without moving the token, and the token is either
 * still 62–70 characters or it quietly stopped being.
 *
 *   node scripts/measure.mjs                    # against http://localhost:8000
 *   SITE=http://localhost:4321 node scripts/measure.mjs
 *
 * Counts where the browser broke the lines rather than dividing the column
 * width by an average glyph, so the number is the text the reader is looking at.
 * Writes docs/verification/measure.json.
 *
 * Both reading densities, since ADR-0054 (`--measure` is a multiple of
 * `--reading-size`, so the *claim* is that the character count does not move
 * when the density does — and a claim measured in one setting only is not
 * measured). Exits non-zero if a median falls outside 62-70 at a width where
 * the column is at its maximum.
 *
 * The band check also runs in `make test-e2e`, which CI runs on every push
 * (`tests/e2e/typography.spec.ts`); the measuring itself is shared with it
 * rather than written twice. What only lives here is `documentHeights`, which
 * is a record rather than a check — and one that had gone three sessions stale
 * without saying so, which is why the artifact now names the commit it was
 * measured at.
 */
import { execFileSync } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { chromium } from "playwright";

import {
  BAND,
  DENSITIES,
  FULL_WIDTH,
  PAGE,
  WIDTHS,
  lineLengths,
  summarise,
  withDensity,
} from "./measure-lines.mjs";

const SITE = process.env.SITE ?? "http://localhost:8000";
const OUT = new URL("../../docs/verification/", import.meta.url);

/**
 * Sections to record the scroll length of.
 *
 * A narrower measure is more lines, and more lines is a longer page — which is
 * the cost ADR-0052 accepts and therefore the number it has to be able to show.
 * Three lengths of section: short, long, and one carrying a table.
 */
const HEIGHTS = ["/app/us/usc/t16/s45f", "/app/us/usc/t16/s470a", "/app/us/usc/t16/s1801"];

/** The commit these heights describe. A scroll length is only comparable to
 * another one taken against the same chrome, and the last three sessions of
 * this file were read as though they were. */
function commit() {
  try {
    const rev = execFileSync("git", ["rev-parse", "--short", "HEAD"], {
      encoding: "utf8",
    }).trim();
    const dirty =
      execFileSync("git", ["status", "--porcelain"], { encoding: "utf8" }).trim().length > 0;
    return dirty ? `${rev}-dirty` : rev;
  } catch {
    return null;
  }
}

const browser = await chromium.launch();
const results = [];
const heights = [];

for (const density of DENSITIES) {
  for (const path of HEIGHTS) {
    for (const width of [375, 1280]) {
      const context = await browser.newContext({ viewport: { width, height: 900 } });
      await withDensity(context, density);
      const page = await context.newPage();
      await page.goto(`${SITE}${path}`, { waitUntil: "networkidle" });
      await page.evaluate(() => document.fonts.ready);
      heights.push({
        page: path,
        density: density ?? "comfortable",
        viewport: width,
        scrollHeightPx: await page.evaluate(() => document.documentElement.scrollHeight),
      });
      await context.close();
    }
  }

  for (const width of WIDTHS) {
    const context = await browser.newContext({ viewport: { width, height: 900 } });
    await withDensity(context, density);
    const page = await context.newPage();
    await page.goto(`${SITE}${PAGE}`, { waitUntil: "networkidle" });
    await page.evaluate(() => document.fonts.ready);

    const column = await page.evaluate(() => {
      const body = document.querySelector(".section-body");
      if (!body) return null;
      const style = getComputedStyle(body);
      return {
        widthPx: Math.round(body.getBoundingClientRect().width),
        fontFamily: style.fontFamily,
        fontSize: style.fontSize,
        lineHeight: style.lineHeight,
      };
    });

    results.push({
      viewport: width,
      density: density ?? "comfortable",
      page: PAGE,
      columnWidthPx: column?.widthPx ?? null,
      fontFamily: column?.fontFamily ?? null,
      fontSize: column?.fontSize ?? null,
      lineHeight: column?.lineHeight ?? null,
      characters: summarise(await lineLengths(page)),
    });
    await context.close();
  }
}

await browser.close();
await mkdir(OUT, { recursive: true });
await writeFile(
  new URL("measure.json", OUT),
  `${JSON.stringify(
    {
      _comment:
        "Generated by frontend/scripts/measure.mjs against a running site. Do not hand-edit " +
        "— re-run it. Characters per rendered line of statutory text, counted from " +
        "Range.getClientRects() rather than estimated from a glyph width. Final lines of a " +
        "paragraph are excluded: they end where the sentence ends, not where the column does. " +
        "ADR-0052 holds the median between 62 and 70 at the widths where the column is at its " +
        "maximum. That check also runs in frontend/tests/e2e/typography.spec.ts, which CI runs " +
        "on every push, over the same measuring code in scripts/measure-lines.mjs. Both reading " +
        "densities are measured (ADR-0054): --measure is a multiple of --reading-size, so the " +
        "character count is supposed to be the same in either, and that is the claim these two " +
        "sets of rows check. documentHeights is the scroll length of three sections at two " +
        "widths, which is what a narrower measure and a tighter leading cost; nothing gates on " +
        "it, so it carries the commit it was measured at — a scroll length is comparable only " +
        "to one taken against the same chrome.",
      site: SITE,
      measuredAt: commit(),
      band: BAND,
      results,
      documentHeights: heights,
    },
    null,
    2,
  )}\n`,
);

let failed = 0;
for (const result of results) {
  const c = result.characters;
  const checked = result.viewport >= FULL_WIDTH;
  const inBand = c.median >= BAND.low && c.median <= BAND.high;
  if (checked && !inBand) failed += 1;
  console.log(
    `${result.density.padEnd(11)} ${String(result.viewport).padStart(4)}px  ` +
      `column ${String(result.columnWidthPx).padStart(4)}px  ${c.lines} lines  ` +
      `median ${c.median}  p10-p90 ${c.p10}-${c.p90}` +
      (checked ? (inBand ? "  ok" : `  OUTSIDE ${BAND.low}-${BAND.high}`) : "  (viewport-bound)"),
  );
}

if (failed) {
  console.error(`\n${failed} measurement(s) outside ${BAND.low}-${BAND.high} characters.`);
  process.exit(1);
}
