"""Contrast ratios for every colour pair the reader puts on screen.

WCAG 2.1 AA asks for 4.5:1 on body text, 3:1 on large text, and 3:1 on the
non-text parts of a user interface — borders, focus rings, the edge of a
highlight. The reader has two palettes (ADR-0027), so every one of those is two
questions, and "it looks fine" answers neither.

The values are read from `frontend/src/styles/site.scss` rather than typed in
here: the token block is the source of truth, and a table maintained beside it
would be wrong the first time somebody nudged a hex.

The list of pairs — which token is painted on which, and what the criterion
asks of that combination — is `frontend/src/data/color-pairs.json`, and is read
rather than declared here because it has a second reader. `/app/design` renders
the same list against the tokens the *running page* resolves, so the two answers
can be compared (ADR-0053); a copy of the list in this file would be a copy that
could disagree with the page about which pairs exist.

    uv run python scripts/contrast.py

Writes docs/verification/contrast.json and exits non-zero if any pair fails, so
it can be run as a check as well as a generator.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STYLES = ROOT / "frontend" / "src" / "styles" / "site.scss"
PAIRS_FILE = ROOT / "frontend" / "src" / "data" / "color-pairs.json"
OUT = ROOT / "docs" / "verification" / "contrast.json"

HEX = re.compile(r"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$")


def read_pairs() -> list[dict]:
    """The declared pairs, in order. `requires: null` is a decorative pair."""
    return json.loads(PAIRS_FILE.read_text(encoding="utf-8"))["pairs"]


def read_tokens() -> dict[str, dict[str, str]]:
    """The light and dark token blocks, as `{theme: {name: value}}`.

    Light is `:root { … }`; dark is `:root[data-theme="dark"] { … }`. Dark
    inherits every token it does not restate, which is why it is layered onto a
    copy of light rather than read on its own.
    """
    text = STYLES.read_text(encoding="utf-8")

    def block(selector: str) -> dict[str, str]:
        start = text.index(selector)
        # The token block runs to the first line that closes it at column 0.
        end = text.index("\n}", start)
        found = {}
        for name, value in re.findall(r"(--[\w-]+):\s*([^;]+);", text[start:end]):
            found[name] = value.strip()
        return found

    light = block(":root {")
    dark = dict(light)
    dark.update(block(':root[data-theme="dark"] {'))
    return {"light": light, "dark": dark}


def to_rgb(value: str) -> tuple[float, float, float]:
    value = value.strip()
    if HEX.match(value):
        digits = value[1:]
        if len(digits) == 3:
            digits = "".join(c * 2 for c in digits)
        return tuple(int(digits[i : i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]
    raise ValueError(f"not an opaque colour: {value!r}")


def luminance(rgb: tuple[float, float, float]) -> float:
    def channel(v: float) -> float:
        v /= 255
        return v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4

    r, g, b = (channel(c) for c in rgb)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def ratio(fg: str, bg: str) -> float:
    a, b = luminance(to_rgb(fg)), luminance(to_rgb(bg))
    lighter, darker = max(a, b), min(a, b)
    return (lighter + 0.05) / (darker + 0.05)


def main() -> None:
    tokens = read_tokens()
    results = []
    failures = []

    def record(fg_name: str, bg_name: str, usage: str, need: float | None) -> None:
        entry: dict = {
            "usage": usage,
            "foreground": fg_name,
            "background": bg_name,
            "requires": need,
        }
        if need is None:
            entry["decorative"] = True
        for theme in ("light", "dark"):
            fg = fg_name if fg_name.startswith("#") else tokens[theme][fg_name]
            bg = bg_name if bg_name.startswith("#") else tokens[theme][bg_name]
            try:
                value = round(ratio(fg, bg), 2)
            except ValueError as error:
                entry[theme] = {"skipped": str(error)}
                continue
            passes = None if need is None else value >= need
            entry[theme] = {"fg": fg, "bg": bg, "ratio": value, "passes": passes}
            if passes is False:
                failures.append(f"{usage} [{theme}]: {fg} on {bg} is {value}:1, needs {need}:1")
        results.append(entry)

    for pair in read_pairs():
        record(pair["foreground"], pair["background"], pair["usage"], pair["requires"])

    report = {
        "_comment": (
            "Generated by scripts/contrast.py. Do not hand-edit — re-run it. Token values are "
            "read from frontend/src/styles/site.scss; the list of pairs is read from "
            "frontend/src/data/color-pairs.json, which /app/design renders against the tokens "
            "the running page resolves (ADR-0053). WCAG 2.1 AA: 4.5:1 for text, 3:1 for large "
            "text and non-text UI parts (1.4.3, 1.4.11). Pairs whose value is not an opaque "
            "colour are reported as skipped rather than guessed at."
        ),
        "source": str(STYLES.relative_to(ROOT)),
        "pairs_declared_in": str(PAIRS_FILE.relative_to(ROOT)),
        "tokens": tokens,
        "pairs": results,
        "summary": {
            "pairs": len(results),
            "checks": len(results) * 2,
            "failures": len(failures),
        },
    }
    OUT.write_text(json.dumps(report, indent=2) + "\n")

    print(f"{len(results)} pairs x 2 themes -> {OUT.relative_to(ROOT)}")
    for entry in results:
        for theme in ("light", "dark"):
            data = entry[theme]
            if "skipped" in data:
                print(f"  SKIP {theme:5} {entry['usage']}: {data['skipped']}")
                continue
            mark = {True: "ok  ", False: "FAIL", None: "deco"}[data["passes"]]
            need = "n/a" if entry["requires"] is None else str(entry["requires"])
            print(
                f"  {mark} {theme:5} {data['ratio']:>6.2f}:1 "
                f"(needs {need}) {entry['usage']}"
            )

    if failures:
        print(f"\n{len(failures)} failing:", file=sys.stderr)
        for line in failures:
            print(f"  {line}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
