"""Which USLM elements occur inside running prose?

`frontend/src/lib/uslm.ts` partitions elements into inline and block, and
anything it does not name falls through to a `<div>`. A `<div>` in the middle of
a sentence breaks the line visually and, worse, reorders the sequence a screen
reader announces (WCAG 1.3.2) — which in the editorial notes is exactly where a
drafter is reading for amendment history.

Guessing at the partition from the schema is how `<date>` was missed once
already. This measures it instead: an element is *inline* if it is ever a child
of a text-bearing element while a non-whitespace text sibling sits beside it.
That is the empirical definition of "in running prose", and it is the same
question the renderer has to answer.

    uv run python scripts/inline_elements.py

Writes docs/verification/inline-elements.json. Reads the committed samples, so
it needs no database and no network.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any

from lxml import etree

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "verification" / "inline-elements.json"

SAMPLES = [
    ("uslm1", ROOT / "samples" / "uslm1" / "usc16.xml"),
    ("uslm2", ROOT / "samples" / "uslm2" / "USLM2" / "usc16.xml"),
    ("uslm2", ROOT / "samples" / "uslm2" / "USLM2" / "usc49.xml"),
    ("uslm2", ROOT / "samples" / "uslm2" / "USLM2" / "usc01.xml"),
]

#: Enough of the surrounding sentence to see that it really is a sentence.
CONTEXT_CHARS = 90


def local(tag: Any) -> str:
    """`{ns}date` -> `date`; comments and PIs have non-string tags."""
    if not isinstance(tag, str):
        return ""
    return tag.rsplit("}", 1)[-1]


def has_text(value: str | None) -> bool:
    return bool(value and value.strip())


def scan(path: Path) -> tuple[dict[str, int], dict[str, int], dict[str, str]]:
    """Count each element's inline and isolated occurrences, and keep a sample.

    *Inline* means a non-whitespace text node sits immediately before or after
    it — the parent's own `.text` for a first child, the previous sibling's
    `.tail` otherwise, and its own `.tail` on the right.
    """
    inline: dict[str, int] = defaultdict(int)
    isolated: dict[str, int] = defaultdict(int)
    sample: dict[str, str] = {}

    for _, el in etree.iterparse(str(path), events=("end",), recover=True):
        name = local(el.tag)
        if not name:
            continue

        previous = el.getprevious()
        before = previous.tail if previous is not None else (
            el.getparent().text if el.getparent() is not None else None
        )
        if has_text(before) or has_text(el.tail):
            inline[name] += 1
            if name not in sample:
                left = (before or "").strip()[-CONTEXT_CHARS:]
                own = "".join(el.itertext()).strip()[:CONTEXT_CHARS]
                right = (el.tail or "").strip()[:CONTEXT_CHARS]
                sample[name] = f"…{left} [{name}]{own}[/{name}] {right}…"
        else:
            isolated[name] += 1

        # Streaming, per gotcha 6: Title 42 is huge and the 32 MB samples here
        # are not the largest thing this will ever be pointed at. Clearing the
        # element would orphan the tails the check above reads, so the parent's
        # already-processed children go instead.
        parent = el.getparent()
        if parent is not None:
            grandparent = parent.getparent()
            while grandparent is not None and parent.getprevious() is not None:
                del grandparent[0]

    return inline, isolated, sample


def main() -> None:
    totals_inline: dict[str, int] = defaultdict(int)
    totals_isolated: dict[str, int] = defaultdict(int)
    samples: dict[str, str] = {}
    per_file: dict[str, dict[str, int]] = {}

    for schema, path in SAMPLES:
        if not path.exists():
            raise SystemExit(f"missing sample: {path}")
        inline, isolated, sample = scan(path)
        per_file[f"{schema}:{path.name}"] = dict(sorted(inline.items()))
        for name, count in inline.items():
            totals_inline[name] += count
        for name, count in isolated.items():
            totals_isolated[name] += count
        for name, text in sample.items():
            samples.setdefault(name, text)

    elements = sorted(totals_inline, key=lambda n: -totals_inline[n])
    report = {
        "_comment": (
            "Generated by scripts/inline_elements.py. An element is listed when it appears "
            "in running prose in the committed samples — a non-whitespace text node "
            "immediately beside it. Every one of these must render inline in "
            "frontend/src/lib/uslm.ts; tests/uslm.test.ts asserts it element by element."
        ),
        "sources": [str(p.relative_to(ROOT)) for _, p in SAMPLES],
        "elements": [
            {
                "name": name,
                "inline": totals_inline[name],
                "isolated": totals_isolated.get(name, 0),
                "sample": samples.get(name, ""),
            }
            for name in elements
        ],
        "perFile": per_file,
    }

    OUT.write_text(json.dumps(report, indent=2) + "\n")
    print(f"{len(elements)} elements occur in running prose -> {OUT.relative_to(ROOT)}")
    for name in elements:
        print(f"  {name:20} inline={totals_inline[name]:<8} isolated={totals_isolated.get(name, 0)}")


if __name__ == "__main__":
    main()
